"""Generate or verify the packaged static Bash completion script."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import shtab

from pytorch_course.cli import create_parser

COURSE_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = COURSE_ROOT / "src" / "pytorch_course" / "completions" / "course.bash"
HEADER = "# Generated by tools/generate_completion.py; do not edit.\n"


def configure_completers(parser: argparse.ArgumentParser) -> None:
    """Add generation-only completers without a runtime shtab dependency."""
    for action in parser._actions:
        if action.type is Path:
            action.complete = shtab.FILE
        if isinstance(action, argparse._SubParsersAction):
            for subparser in action.choices.values():
                configure_completers(subparser)


def render_completion() -> str:
    """Render deterministic Bash completion from the canonical CLI parser."""
    parser = create_parser()
    configure_completers(parser)
    return HEADER + shtab.complete(parser, shell="bash").rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    """Generate the script, or fail when a checked-in script is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in script instead of replacing it",
    )
    args = parser.parse_args(argv)
    rendered = render_completion()

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != rendered:
            print(
                "Bash completion is stale; run tools/generate_completion.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(COURSE_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
